// Contenido de las 7 herramientas de DBT, redactado con palabras propias
// (ver CLAUDE.md de "Herramientas Emocionales" — reescrito 2026-09-17 para
// poder vivir en una app, no es texto extraído del manual de Linehan).
const TOOLS = {
  stop: {
    title: 'STOP',
    subtitle: 'Para no reaccionar en caliente',
    icon: '🛑',
    group: 'Bajar la intensidad ahora',
    steps: [
      { letter: 'S', name: 'Frená', body: 'Cortá el movimiento, literal. No respondas todavía, no escribas el mensaje, no tomes la decisión. El cuerpo quieto le saca combustible al impulso.' },
      { letter: 'T', name: 'Tomá distancia', body: 'Un paso atrás de la situación, unos segundos o minutos. Salir físicamente del lugar si se puede, respirar antes de seguir.' },
      { letter: 'O', name: 'Observá', body: 'Qué está pasando, en vos y afuera. Qué sentís, qué pensás, qué está haciendo o diciendo la otra persona, cuál es el hecho concreto (no la interpretación).' },
      { letter: 'P', name: 'Procedé con cabeza fría', body: 'Elegí la acción mirando el objetivo de fondo, no el impulso del momento. Preguntate "¿esto me acerca o me aleja de lo que quiero?" antes de actuar.' },
    ],
  },
  tip: {
    title: 'TIP',
    subtitle: 'Para bajar la intensidad física ya',
    icon: '❄️',
    group: 'Bajar la intensidad ahora',
    steps: [
      { letter: 'T', name: 'Temperatura', body: 'Enfriar el cuerpo de golpe (agua fría en la cara, aguantando la respiración un rato corto) — el frío activa una respuesta del sistema nervioso que baja la frecuencia cardíaca rápido.' },
      { letter: 'I', name: 'Movimiento intenso', body: 'Gastar esa energía con algo físico y corto — correr en el lugar, saltar, lo que sea que suba el pulso unos minutos.' },
      { letter: 'P', name: 'Respiración larga', body: 'Inhalar corto, exhalar más largo. Alargar la exhalación es lo que activa la calma, no la respiración en sí.' },
      { letter: 'P', name: 'Relajación por partes', body: 'Tensar un grupo de músculos a propósito y soltarlo de golpe, notando el contraste. Repetir por zonas del cuerpo.' },
    ],
    note: 'Ojo con el frío si hay alguna condición cardíaca, medicación que afecte el ritmo cardíaco, o un trastorno alimentario — ahí conviene chequear con un médico antes.',
  },
  aceptas: {
    title: 'ACEPTAS',
    subtitle: 'Distraerte para aguantar sin empeorarlo',
    icon: '🌀',
    group: 'Aguantar sin empeorar',
    intro: 'La idea es correr el foco de la mente mientras la ola pasa, sin evitar el problema para siempre, solo por ahora.',
    steps: [
      { letter: 'A', name: 'Actividades', body: 'Meterte en algo que te absorba (algo pendiente, salir, moverte, un juego).' },
      { letter: 'C', name: 'Contribuciones', body: 'Hacer algo por otra persona — el foco en el otro saca el foco de vos.' },
      { letter: 'E', name: 'Emociones distintas', body: 'Buscar a propósito una emoción distinta (algo que te haga reír, música que cambie el clima interno).' },
      { letter: 'P', name: 'Otros Pensamientos', body: 'Ocupar la cabeza con otra cosa (contar, un problema para resolver, algo que pida atención).' },
      { letter: 'T', name: 'Tomar distancia', body: 'Imaginar que guardás el problema en un cajón por un rato, no que desaparece, que espera.' },
      { letter: 'A', name: 'Analogías', body: 'Compararte con un momento peor que ya atravesaste, o con alguien que esté pasando algo más difícil — no para minimizar, para recalibrar.' },
      { letter: 'S', name: 'Sensaciones', body: 'Generar otra sensación física fuerte que compita con la emocional (algo frío en la mano, sonido fuerte, cambio brusco de temperatura en la ducha).' },
    ],
  },
  salvara: {
    title: 'SALVARA',
    subtitle: 'Mejorar el momento mientras dura',
    icon: '🕯️',
    group: 'Aguantar sin empeorar',
    steps: [
      { letter: 'S', name: 'Significado', body: 'Buscarle un sentido a lo que duele, aunque sea después.' },
      { letter: 'A', name: 'Aliento', body: 'Repetirte que esto es temporal, que ya pasaste momentos así antes.' },
      { letter: 'L', name: 'Lugar seguro', body: 'Imaginar un lugar donde te sentís seguro/a, con detalle.' },
      { letter: 'V', name: 'Vez (una a la vez)', body: 'Ir de a una cosa a la vez, no todo el problema junto.' },
      { letter: 'A', name: 'Alto', body: 'Darte un corte, una pausa breve del problema, como unas vacaciones cortas.' },
      { letter: 'R', name: 'Rezar', body: 'Si rezar o algo espiritual es parte tuya, usarlo.' },
      { letter: 'A', name: 'Acciones relajantes', body: 'Hacer algo que sepas que te relaja, lo que sea que ya te funcionó antes.' },
    ],
  },
  dearman: {
    title: 'DEAR MAN',
    subtitle: 'Conseguir algo puntual (pedir, poner un límite, decir que no)',
    icon: '🎯',
    group: 'Comunicarte con tu pareja',
    steps: [
      { letter: 'D', name: 'Describí', body: 'El hecho, sin juicio ni interpretación — lo que pasó, no lo que significa.' },
      { letter: 'E', name: 'Expresá', body: 'Cómo te sentís en primera persona ("yo siento", no "vos me hacés sentir").' },
      { letter: 'A', name: 'Asertivo/a', body: 'Pedí o negá con claridad — nadie adivina lo que necesitás si no lo decís directo.' },
      { letter: 'R', name: 'Reforzá', body: 'Mostrá qué gana el otro si acepta lo que pedís — no es manipulación, es dar un motivo real.' },
      { letter: 'M', name: 'Mantené el foco', body: 'Sostené el punto aunque la conversación se estire, sin ceder solo por cansancio.' },
      { letter: 'A', name: 'Aparentá seguridad', body: 'Mantené la postura con el cuerpo y el tono, aunque por dentro haya dudas.' },
      { letter: 'N', name: 'Negociá', body: 'Dejá lugar a negociar — llegar a algo que sirva a ambos suele valer más que ganar entero.' },
    ],
  },
  aves: {
    title: 'AVES',
    subtitle: 'Cuidar la relación mientras pedís algo',
    icon: '🕊️',
    group: 'Comunicarte con tu pareja',
    steps: [
      { letter: 'A', name: 'Atención', body: 'Prestá atención real — escuchá, mirá a los ojos, no interrumpas para armar tu respuesta.' },
      { letter: 'V', name: 'Validá', body: 'Lo que el otro siente o piensa, aunque no estés de acuerdo — mostrar que entendiste su punto no es ceder el tuyo.' },
      { letter: 'E', name: 'Educadamente', body: 'El tono importa tanto como el contenido.' },
      { letter: 'S', name: 'Sin dureza', body: 'Nada de ataques, amenazas, ironía, caras o gestos que bajen línea moral.' },
    ],
  },
  vida: {
    title: 'VIDA',
    subtitle: 'Salir de la conversación sin perderte a vos mismo/a',
    icon: '🧭',
    group: 'Comunicarte con tu pareja',
    steps: [
      { letter: 'V', name: 'Valores primero', body: 'No cedas algo que te importa de verdad solo por evitar el conflicto.' },
      { letter: 'I', name: 'Imparcial', body: 'Parejo con ambos — validá tu propia postura tanto como la del otro, no seas más duro/a con vos que con ellos.' },
      { letter: 'D', name: 'Sin disculparte de más', body: 'Pedir, opinar distinto o poner un límite no son motivo de disculpa.' },
      { letter: 'A', name: 'Auténtico/a', body: 'Sin exagerar para convencer, sin hacerte el/la indefenso/a si no lo sos.' },
    ],
  },
  mentesabia: {
    title: 'Mente Sabia',
    subtitle: 'Los tres estados de tu mente',
    icon: '🧘',
    group: 'Conciencia plena (mindfulness)',
    steps: [
      { letter: '1', name: 'Mente Racional', body: 'Fría, lógica, se guía por hechos y objetivos. Cuando estás acá, los sentimientos quedan afuera de la decisión — a veces eso te sirve, a veces te deja corto/a.' },
      { letter: '2', name: 'Mente Emocional', body: 'Caliente, se guía por el estado de ánimo y el impulso del momento. Cuando estás acá, los hechos y la lógica pesan poco al lado de lo que sentís ahora.' },
      { letter: '3', name: 'Mente Sabia', body: 'El punto donde las dos se cruzan — no ignora la razón ni la emoción, las junta. Ya está en vos, aunque cueste encontrarla en caliente.' },
      { letter: '4', name: 'Encontrarla', body: 'Antes de decidir algo importante, hacé la pregunta: no "¿qué dice la lógica?" ni "¿qué tengo ganas?", sino "¿qué diría mi mente sabia?".' },
    ],
  },
  quepracticar: {
    title: 'Qué observar',
    subtitle: 'Las tres formas de prestar atención',
    icon: '👁️',
    group: 'Conciencia plena (mindfulness)',
    steps: [
      { letter: '1', name: 'Observar', body: 'Notar lo que pasa, adentro y afuera, sin ponerle palabras todavía — solo registrar la sensación, el pensamiento, lo que ves, dejando que entre y salga como una ola.' },
      { letter: '2', name: 'Describir', body: 'Ahora sí, ponerle palabras a lo que observaste — separando el hecho de la interpretación ("se me tensó la mandíbula", no "esto es un desastre").' },
      { letter: '3', name: 'Participar', body: 'Meterte de lleno en lo que estás haciendo, sin quedarte mirándote desde afuera — dejar de analizarte y simplemente hacer, con lo que ya sabés.' },
    ],
  },
  comopracticar: {
    title: 'Cómo prestar atención',
    subtitle: 'El estilo, no el qué',
    icon: '⚖️',
    group: 'Conciencia plena (mindfulness)',
    steps: [
      { letter: '1', name: 'Sin juzgar', body: 'Notar los hechos sin etiquetarlos de bueno/malo. Se puede reconocer que algo es peligroso o te hace mal sin necesidad de juzgarlo — y si te descubrís juzgando, tampoco hace falta juzgar eso.' },
      { letter: '2', name: 'Una cosa a la vez', body: 'Lo que estés haciendo, hacé solo eso. Si la cabeza se va a otro lado (a planear, a preocuparse, a recordar), volver una y otra vez a lo de ahora.' },
      { letter: '3', name: 'Siendo efectivo/a', body: 'Hacer lo que funciona en la situación real que tenés, no en la que te gustaría tener. Soltar el "tengo razón" o la terquedad cuando no te está ayudando a nada.' },
    ],
  },
  entenderemocion: {
    title: 'Entender tu emoción',
    subtitle: 'De dónde viene lo que sentís',
    icon: '🔍',
    group: 'Entender y cambiar lo que sentís',
    steps: [
      { letter: '1', name: 'Lo que ya traías', body: 'Cómo llegaste a la situación (cansado/a, con hambre, con otra bronca de antes) cambia cuánto te afecta lo que pase después.' },
      { letter: '2', name: 'El hecho y tu interpretación', body: 'No es solo lo que pasó, es lo que pensaste que significaba. Dos personas pueden vivir el mismo evento y sentir cosas distintas según cómo lo interpretan.' },
      { letter: '3', name: 'Cómo se nota', body: 'En el cuerpo (se acelera el corazón, se tensan los músculos), en la cara y la postura, en lo que decís y en lo que hacés.' },
      { letter: '4', name: 'Ponerle nombre', body: 'Nombrar la emoción (bronca, miedo, tristeza) ayuda a tomar distancia de ella — deja de ser "todo vos" y pasa a ser algo que estás sintiendo.' },
      { letter: '5', name: 'Lo que viene después', body: 'La emoción deja consecuencias: otro pensamiento, otra emoción, cómo terminaste actuando. Cambiar cualquier eslabón de esta cadena cambia el resultado final.' },
    ],
  },
  verificarhechos: {
    title: 'Verificar los hechos',
    subtitle: 'Chequear si la emoción se ajusta a lo que pasó de verdad',
    icon: '🔎',
    group: 'Entender y cambiar lo que sentís',
    steps: [
      { letter: '1', name: '¿Qué emoción?', body: 'Nombrá primero la emoción que querés revisar.' },
      { letter: '2', name: '¿Cuál es el hecho?', body: 'Solo lo que viste u oíste, sin la interpretación — el "qué, quién, cuándo, dónde" nomás.' },
      { letter: '3', name: '¿Qué interpretación le diste?', body: 'Pensá si hay otras lecturas posibles del mismo hecho, y si la tuya realmente se ajusta a él.' },
      { letter: '4', name: '¿Hay una amenaza asumida?', body: 'Ponele nombre a esa amenaza y pensá qué tan probable es que pase de verdad, no solo que podría pasar.' },
      { letter: '5', name: '¿Cuál sería la catástrofe?', body: 'Imaginala en detalle — y también imaginate afrontándola, si de verdad pasara.' },
      { letter: '6', name: '¿Se ajusta a los hechos?', body: 'Si la emoción (o su intensidad) no se ajusta a lo que realmente pasó, ese es tu indicio para probar con Acción Opuesta.' },
    ],
  },
  accionopuesta: {
    title: 'Acción Opuesta',
    subtitle: 'Cuando la emoción no se ajusta a los hechos, o seguirla no te conviene',
    icon: '🔄',
    group: 'Entender y cambiar lo que sentís',
    intro: 'Cada emoción viene con un impulso: miedo empuja a evitar, enojo a atacar, tristeza a aislarte, vergüenza a esconderte. Hacer lo opuesto a ese impulso, a propósito y del todo, puede cambiar la emoción misma.',
    steps: [
      { letter: '1', name: 'Identificá la emoción', body: 'Nombrá la que querés cambiar.' },
      { letter: '2', name: 'Verificá los hechos', body: '¿Esa emoción está justificada por lo que realmente pasó, en tipo e intensidad?' },
      { letter: '3', name: 'Identificá el impulso', body: 'Qué te están dando ganas de hacer — el impulso de acción de esa emoción.' },
      { letter: '4', name: 'Preguntale a tu mente sabia', body: '¿Seguir ese impulso te conviene en esta situación puntual?' },
      { letter: '5', name: 'Buscá la acción opuesta', body: 'Si no se ajusta a los hechos o no te conviene: ¿cuál sería lo opuesto a ese impulso? (miedo→abordar, enojo→ser amable, tristeza→activarte, vergüenza→contarlo a quien lo va a aceptar).' },
      { letter: '6', name: 'Hacela completa', body: 'No a medias — actuar un poquito distinto no alcanza para cambiar la emoción.' },
      { letter: '7', name: 'Repetila', body: 'Las veces que haga falta, hasta que la emoción efectivamente cambie.' },
    ],
  },
  acacuida: {
    title: 'ACA + CUIDA',
    subtitle: 'Bajar el volumen de fondo, para no reaccionar tan fuerte en general',
    icon: '🌱',
    group: 'Entender y cambiar lo que sentís',
    steps: [
      { letter: 'A', name: 'Acumulá momentos buenos', body: 'Metete cosas agradables en el día de hoy, aunque sean chiquitas — y de a poco, cambios más de fondo para que pasen más seguido.' },
      { letter: 'C', name: 'Construí manejo', body: 'Hacé cosas que te hagan sentir capaz y efectivo/a, para contrarrestar la sensación de que nada te sale.' },
      { letter: 'A', name: 'Anticipate', body: 'Si sabés que se viene algo difícil, planealo antes con calma — no lo improvises en el momento.' },
      { letter: 'C', name: 'Cuidá tu cuerpo', body: 'Chequeos médicos al día, no postergues lo físico.' },
      { letter: 'U', name: 'No uses sustancias', body: 'Nada que te cambie el humor artificialmente (alcohol incluido) para tapar lo que sentís.' },
      { letter: 'I', name: 'Intentá ejercitarte', body: 'Aunque sea un poco, todos los días.' },
      { letter: 'D', name: 'Dormí equilibrado', body: 'Lo que necesitás, con horarios parejos.' },
      { letter: 'A', name: 'Alimentate bien', body: 'Ni de más ni de menos — ojo con lo que te dispara el humor (azúcar, cafeína).' },
    ],
  },
  surfearemocion: {
    title: 'Surfear la emoción',
    subtitle: 'Dejar que pase, sin pelearla ni alimentarla',
    icon: '🌊',
    group: 'Entender y cambiar lo que sentís',
    steps: [
      { letter: '1', name: 'Es una ola', body: 'Notá la emoción como una ola: sube, tiene un pico, y baja sola si no la seguís empujando.' },
      { letter: '2', name: 'Sentila en el cuerpo', body: 'Dónde la notás físicamente, sin escaparte de la sensación.' },
      { letter: '3', name: 'Vos no sos tu emoción', body: 'Es algo que está pasando por vos ahora, no todo lo que sos.' },
      { letter: '4', name: 'No la juzgues', body: 'Dejala ser, sin apurarte a que se vaya ni aferrarte a que se quede.' },
    ],
  },
};

const TOOL_ORDER = [
  'mentesabia', 'quepracticar', 'comopracticar',
  'stop', 'tip', 'aceptas', 'salvara',
  'entenderemocion', 'verificarhechos', 'accionopuesta', 'acacuida', 'surfearemocion',
  'dearman', 'aves', 'vida',
];
